version: "3"
services:

  chrome:
    image: selenium/standalone-chrome
    volumes:
        - /dev/shm:/dev/shm
    ports:
        - "4444:4444"
        - "7900:7900"

  app:
    build: .
    volumes:
        - .:/app
    restart: always
    ports:
        - "8080:8080"
